- name: Running Docker containers
  docker_container:
    name: "{{ item.name }}_container"
    image: "{{ item.name }}_image"
    state: started
    ports:
      - "{{ item.port }}:80"
  loop: "{{ docker_images }}"
  loop_control:
    loop_var: item

