---
- name: Check and Install Docker
  hosts: all
  become: true

  tasks:
    - name: Check if Docker is installed
      stat:
        path: /usr/bin/docker
      register: docker_check

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_check.stat.exists == false

    - name: Add user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      when: docker_check.stat.exists == true  
    - name: Update list  apt
      apt:
        update_cache: yes

    - name: Installing Python
      apt:
        name: python3
        state: present

    - name: Installing pip
      apt:
        name: python3-pip
        state: present

    - name: Installing module Docker
      pip:
        name: docker
        state: present
